### ISSUE TITLE
Black market doesn't work

### ISSUE THREAD

**Issue by KBalage** [ValkDes/ValkyrieCOB#1]
Black market doesn't work. We tried to get access to black market as the offer never good enough (no weapons offered at all). Took our 50 Gold, but nothing happened.
Message came "You are able to find another merchant", but nothing happens, no change in offer, no new option appears.
![black_market](https://user-images.githubusercontent.com/106810901/232056294-af8dcc6a-9394-4ed3-9303-cf12c51817dd.png)

**Comment by ValkDes** [comment]
Won't fix: 

This is directly related to #5. Going to the black market normally restocks the market but because of the other bug not market options where available at all.
