### ISSUE TITLE
No instrucions in between Encounter 1 and 2A or 2B in Hallowing Fire

### ISSUE THREAD

**Issue by KBalage** [ValkDes/ValkyrieCOB#3]
We have won Encounter1 for Hallowing Fire. There were no instructions what to do with Conditions, Knocked out heroes (if any), Fatigue, Health, etc. - The usual stuff which normally happens in between encounters. 
We did it by the book - but it would be nice if the Quest text would mention it.

**Comment by ValkDes** [comment]
Fixed. New version will be uploaded later today.
