### ISSUE TITLE
Map tile alignment

### ISSUE THREAD

**Issue by KBalage** [ValkDes/ValkyrieCOB#6]
A wee misalignment in for tile 92A:

![image](https://user-images.githubusercontent.com/106810901/232223921-ef0a922a-c765-4409-94bf-3c970d553d67.png)

**Comment by KBalage** [comment]
Crumbling terrain is placed wrongly, it supposed to be there:
![image](https://user-images.githubusercontent.com/106810901/232224239-d09811a6-a48b-4530-a57c-21b6f0e25984.png)

**Comment by ValkDes** [comment]
> A wee misalignment in for tile 92A:

Won't fix. This is a misaligned tile in Valkyrie. Only a Valkyrie update can fix it.

> Crumbling terrain is placed wrongly, it supposed to be there:

Fixed. New version will be uploaded later today.
