### ISSUE TITLE
Seeking Sanctuary - desecrated reliquary still provides benefit

### ISSUE THREAD

**Issue by KBalage** [ValkDes/ValkyrieCOB#9]
According to the mission instructions a desecrated reliquary should not provide benefits to the heroes - yet it's happening here for the red reliquary.

![image](https://user-images.githubusercontent.com/106810901/232247186-8fbf1189-8aa4-4a96-86bb-e255edd9d888.png)

**Comment by ValkDes** [comment]
Fixed. New version will be uploaded later today.
